<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Water Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>11</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>240.33870638034614</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>4.640688809698538</KnownMass>
                    <Density>1050.0</Density>
                    <Material>Polystyrene</Material>
                    <Name>Paper Cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>4.640688809698538</CalcMass>
                    <CalcCG>30.662119969443236</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>60.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>3</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>0.2286</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Bagel</Name>
                            <KnownCG>70.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>70.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>40.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>25.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Unspecified</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>107.0</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>35.620051127641084</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Plastic Bottle tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>35.620051127641084</CalcMass>
                    <CalcCG>160.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>320.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>106.68</OD>
                    <ID>106.045</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>106.045</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Water</Name>
                            <KnownCG>320.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>320.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>39.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <CustomFinSet>
                            <KnownMass>27.0198</KnownMass>
                            <Density>170.0</Density>
                            <Material>Balsa</Material>
                            <Name>Freeform fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-20.00000000000001</Xb>
                            <CalcMass>27.0198</CalcMass>
                            <CalcCG>115.40770101925254</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>6</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>140.0,0.0|200.0,60.0|200.0,102.0|105.0,102.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>25.0</KnownMass>
                            <Density>1050.0</Density>
                            <Material>Polystyrene</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>160.0</Xb>
                            <CalcMass>18.547678910972024</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>106.045</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>12.062254710494981</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Bottle Funnel</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>12.062254710494981</CalcMass>
                    <CalcCG>22.976279643801853</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>50.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>8</SerialNo>
                    <ShapeCode>5</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>0.762</WallThickness>
                    <ShapeParameter>0.9</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>106.68</FrontDia>
                    <RearDia>31.622999999999998</RearDia>
                </Transition>
                <Transition>
                    <KnownMass>1.122852922975072</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Bottle Neck</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1.122852922975072</CalcMass>
                    <CalcCG>5.030721859444374</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>10.414</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>9</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.143</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>31.622999999999998</FrontDia>
                    <RearDia>26.0096</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>3.986557673815989</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Threaded Portion</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>3.986557673815989</CalcMass>
                    <CalcCG>12.5984</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>25.1968</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>25.654</OD>
                    <ID>21.59</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>21.59</MotorDia>
                    <EngineOverhang>-6.35</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>1.8200790326643088</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Finger grip</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>1.8200790326643088</CalcMass>
                            <CalcCG>1.524</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>3.048</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>37.1856</OD>
                            <ID>25.654</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>